const { ERROR, OFF } = require("../values");

module.exports = {
	rules: {
		"accessor-pairs": ERROR,
		"array-callback-return": ERROR,
		"block-scoped-var": ERROR,
		"complexity": [ERROR, 10],
		"consistent-return": ERROR,
		"curly": [ERROR, "all"],
		"dot-notation": ERROR,
		"eqeqeq": ERROR,
		"guard-for-in": ERROR,
		"max-classes-per-file": ERROR,
		"no-alert": ERROR,
		"no-caller": ERROR,
		"no-div-regex": ERROR,
		"no-else-return": ERROR,
		"no-empty-function": ERROR,
		"no-eval": ERROR,
		"no-extend-native": ERROR,
		"no-extra-bind": ERROR,
		"no-extra-label": ERROR,
		"no-floating-decimal": ERROR,
		"no-implicit-coercion": ERROR,
		"no-implicit-globals": ERROR,
		"no-implied-eval": ERROR,
		"no-iterator": ERROR,
		"no-labels": ERROR,
		"no-lone-blocks": ERROR,
		"no-loop-func": ERROR,
		"no-magic-numbers": [ERROR, { ignore: [0, 1, -1], ignoreArrayIndexes: true }],
		"no-multi-spaces": ERROR,
		"no-multi-str": ERROR,
		"no-new-func": ERROR,
		"no-new-wrappers": ERROR,
		"no-octal-escape": ERROR,
		"no-param-reassign": [ERROR, { props: false }],
		"no-proto": ERROR,
		"no-return-assign": ERROR,
		"no-return-await": ERROR,
		"no-script-url": ERROR,
		"no-self-compare": ERROR,
		"no-sequences": ERROR,
		"no-throw-literal": ERROR,
		"no-unmodified-loop-condition": ERROR,
		"no-unused-expressions": ERROR,
		"no-useless-call": ERROR,
		"no-useless-concat": ERROR,
		"no-useless-return": ERROR,
		"no-void": ERROR,
		"no-warning-comments": ERROR,
		"prefer-promise-reject-errors": ERROR,
		"radix": ERROR,
		"require-await": ERROR,
		"vars-on-top": ERROR,
		"yoda": ERROR,
		"strict": ERROR,
		"callback-return": ERROR,
		"unicorn/custom-error-definition": ERROR,
		"unicorn/filename-case": ERROR,
		"unicorn/no-fn-reference-in-iterator": ERROR,
		"unicorn/no-unused-properties": ERROR,
		"unicorn/prevent-abbreviations": OFF
	},
	plugins: ["unicorn"],
	extends: ["eslint:recommended", "plugin:unicorn/recommended"]
};
